version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  tests:
    build: .
    command: python test_api.py
    depends_on:
      - backend

volumes:
  pgdata: